### ISSUE TITLE
[story] timelogs

### ISSUE THREAD

**Issue by AdamSulek** [AdamSulek/timelogs#33]
- [ ] create insert data into database #5 
- [ ] connecting and fetching of messages from Slack #6 
- [ ] checking insertion into database (validation) #9 
- [ ] prefect tasks - sequention of task #10 
- [ ] add me function #16 
- [ ] optimizing the message reading / new timestamps #15
